[tool.ruff]
# Ruff configuration
target-version = "py38"
line-length = 88
select = ["E", "F", "W", "C", "I"]
ignore = []

# Exclude test directories from certain checks
exclude = [".git", "__pycache__", "build", "dist", "venv", ".venv"]

[tool.ruff.per-file-ignores]
"tests/**/*.py" = ["E501", "W291", "W292", "W293", "I001", "C901", "C414"]
"scripts/**/*.py" = ["E501", "I001", "C901"]
"test_rate_limiting.py" = ["E501", "W291", "W293", "I001"]
"run_tests.py" = ["I001", "W293"]
"run_tests_safe.py" = ["E501"]
"fix_dependencies.py" = ["E501", "W293"]

[tool.bandit]
# Bandit security linter configuration
skips = ["B101"] # Skip assert usage warnings in test files

[tool.bandit.assert_used]
# Allow assert statements in test files
exclude_dirs = ["tests"]
