allow_network: true
api_port: 8001
cache_dir: backend/cache
chunk_overlap: 200
chunk_size: 1500
continuous_mode: false
embed_model: sentence-transformers/all-MiniLM-L6-v2
gpu: true
malicious_key: hack_attempt
model_backend: new-model
model_path: backend/models/llama-7b.gguf
similarity_threshold: 0.8
top_k: 10
vault_path: ./new_vault
vector_db: chroma
