allow_network: true
model_backend: new-model
model_path: models/llama-7b.gguf
embed_model: sentence-transformers/all-MiniLM-L6-v2
vector_db: chroma
api_port: 8000
gpu: false
cache_dir: cache
top_k: 10
chunk_size: 2000
chunk_overlap: 200
similarity_threshold: 0.8
continuous_mode: false
vault_path: test_vault
