name: Scheduled Benchmark Metrics

permissions:
  contents: read
  actions: write  # For uploading artifacts

on:
  schedule:
    - cron: '0 3 * * 1'  # Every Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-benchmark
      - name: Run pytest-benchmark
        run: |
          python -m pytest --benchmark-only --benchmark-save=latest
      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: .benchmarks/latest/results.json
      - name: (Optional) Update metrics docs
        run: |
          python scripts/update_test_metrics.py --apply --skip-pytest --duration "0.0s" --coverage "N/A"
        continue-on-error: true
